config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"
  devise_for :users, only: :omniauth_callbacks,
             controllers: {omniauth_callbacks: "users/omniauth_callbacks"}

  scope "(:locale)", locale: /en|vi/ do

    devise_for :users, skip: :omniauth_callbacks, controllers: {
      registrations: "users/registrations",
      sessions: "users/sessions",
      passwords: "users/passwords"
    }
    resources :upgrade_accounts, only: :update

    root "movies#index"
    get "/movies/:slug", to: "movies#show", as: :movie
    get "/movies/watch/:slug", to: "movies#watch", as: :watch

    resources :search, only: :index

    resources :favoriate_movies, :bookmark_movies, only: %i(index create destroy)

    resources :rates, only: %i(create destroy)

    resources :movies do
      resources :comments, only: %i(create destroy)
    end
    resources :comments do
      resources :comments, only: %i(create destroy)
    end

    namespace :admin do
      root "dashboards#index"
      resources :movies do
        patch "lock", on: :member
      end
      resources :notifications do
        post "read_all", on: :collection
      end
    end
    match "*unmatched", to: "application#rescue_404_exception", via: :all
  end
end

app/controllers/favoriate_movies_controller.rb
class FavoriateMoviesController < ApplicationController
  load_and_authorize_resource
  before_action :find_movie, only: %i(create destroy)
  before_action :find_favoriate_movie, only: :destroy

  def index
    id_favorite = current_user.favoriate_movies.favoriate.pluck :movie_id
    @favoriate_movies = Movie.by_id(id_favorite)
                             .page(params[:page]).per Settings.favorite
  end

  def create
    @favorite_movie = current_user.favoriate_movies.build favorite_movie_params

    if @favorite_movie.save
      flash.now[:success] = t ".success"
    else
      flash.now[:danger] = t ".failed"
    end
    respond_to :js
  end

  def destroy
    if @favoriate.destroy
      flash.now[:success] = t ".success"
    else
      flash.now[:danger] = t ".failed"
    end
    respond_to :js
  end

  private

  def find_movie
    @movie = Movie.find params[:movie_id]
  end

  def find_favoriate_movie
    @favoriate = current_user
                 .favoriate_movies
                 .find_by(movie_id: params[:movie_id],
                          typelike: params[:typelike])
    return if @favoriate

    flash[:danger] = t ".not_found"
    redirect_to root_path
  end

  def favorite_movie_params
    params.permit FavoriateMovie::FAVORITE_PERMIT
  end
end

app/views/favoriate_movies/_favoriate.html.erb
<% if user_signed_in? %>
  <% if current_user.liked? @movie, Settings.enum_favoriate %>
    <%= form_tag favoriate_movie_path(@movie), method: :delete, remote: true do |f| %>
      <%= hidden_field_tag :movie_id, @movie.id %>
      <%= hidden_field_tag :typelike, "favoriate" %>
      <%= button_to "", class:"btn-heart" do %>
        <%= fa_icon "heart", id:"icon-heart-red" %>
      <% end %>
    <% end %>
  <% else %>
  <%= form_for current_user.favoriate_movies.new, remote: true do |f| %>
      <%= hidden_field_tag :movie_id, @movie.id %>
      <%= hidden_field_tag :typelike, "favoriate" %>
      <%= button_to "", class:"btn-heart" do %>
        <%= fa_icon "heart", id:"icon-heart-white" %>
      <% end %>
    <% end %>
  <% end %>
<% else %>
  <%= fa_icon "heart", id:"heart-white" %>
<% end %>

app/views/favoriate_movies/create.js.erb
$('#favoriate-movie').html('<%= j render partial: "favoriate_movies/favoriate", movie: @movie  %>')
$('#toastr').html('<%= j render "shared/toastr" %>');

app/views/favoriate_movies/destroy.js.erb
$('#favoriate-movie').html('<%= j render partial: "favoriate_movies/favoriate", movie: @movie %>')
$('#toastr').html('<%= j render "shared/toastr" %>');

app/views/favoriate_movies/index.html.erb
<br>
<div class="container" id="search-container">
  <div class="row">
    <div class="col-3">
      <div class="result">
        <h5 class="align-bottom">
          <%= t ".favoriate_movies" %>
          <span id="count-favoriate"><%= @favoriate_movies.total_count %></span>
        </h3>
      </div>
    </div>

    <!--content-->
    <div class="col-9">
      <%= render partial: "favoriate_movies/movie", collection: @favoriate_movies, as: :movie %>
    </div>
  </div>
</div>