config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"
  devise_for :users, only: :omniauth_callbacks,
             controllers: {omniauth_callbacks: "users/omniauth_callbacks"}

  scope "(:locale)", locale: /en|vi/ do

    devise_for :users, skip: :omniauth_callbacks, controllers: {
      registrations: "users/registrations",
      sessions: "users/sessions",
      passwords: "users/passwords"
    }
    resources :upgrade_accounts, only: :update

    root "movies#index"
    get "/movies/:slug", to: "movies#show", as: :movie
    get "/movies/watch/:slug", to: "movies#watch", as: :watch

    resources :search, only: :index

    resources :favoriate_movies, :bookmark_movies, only: %i(index create destroy)

    resources :rates, only: %i(create destroy)

    resources :movies do
      resources :comments, only: %i(create destroy)
    end
    resources :comments do
      resources :comments, only: %i(create destroy)
    end

    namespace :admin do
      root "dashboards#index"
      resources :movies do
        patch "lock", on: :member
      end
      resources :notifications do
        post "read_all", on: :collection
      end
    end
    match "*unmatched", to: "application#rescue_404_exception", via: :all
  end
end

app/controllers/admin/movies_controller.rb
class Admin::MoviesController < AdminController
  authorize_resource
  before_action :find_movie, except: %i(index create new)
  before_action :load_data, only: %i(index new edit)
  before_action :load_notify, only: :index

  def index
    @q = Movie.unscoped.ordered_by_create
              .search params[:q], auth_object: set_ransack_auth_object
    @movies = @q.result.includes(:genre).page(params[:page]).per Settings.five
  end

  def new
    @movie = Movie.unscoped.new
  end

  def create
    @movie = Movie.unscoped.new movie_params
    if @movie.save
      flash[:success] = ".success"
      redirect_to admin_movies_path
    else
      flash.now[:danger] = ".error"
      render :new
    end
  end

  def edit; end

  def update
    if @movie.update movie_params
      flash[:success] = ".movie_updated"
      redirect_to admin_movies_path
    else
      flash[:danger] = t ".movie_update_fail"
      render :edit
    end
  end

  def destroy
    if @movie.destroy
      flash[:success] = t ".movie_deleted"
    else
      flash[:danger] = t ".fail"
    end
    respond_to :js
  end

  def lock
    if @movie.update status: params[:status]
      UserWorker.perform_async @movie.id
      flash[:success] = t ".success"
    else
      flash[:danger] = t ".fail"
    end
    respond_to :js
  end

  private

  def movie_params
    params.require(:movie).permit Movie::MOVIE_PERMIT
  end

  def find_movie
    @movie = Movie.unscoped.find params[:id]
  end

  def load_data
    @genre = Genre.all
  end

  def load_notify
    @notification = Notification.unread.ordered_by_create
                                .page(params[:page]).per Settings.five
  end

  def set_ransack_auth_object
    :admin if current_user.admin?
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  load_and_authorize_resource

  def index
    @q = Movie.ransack params[:q]
    @movies = @q.result.ordered_by_view.page(params[:page]).per Settings.five
  end

  def show
    @movie = Movie.includes(:casts).find_by slug: params[:slug]
    @recommend = Genre.includes(:movies).find_by id: @movie.genre_id
  end

  def watch
    @movie = Movie.find_by slug: params[:slug]
    Movie.update_counters [@movie.id], view: Settings.movie.inc_view_per
    @comments = @movie.comments

    return if @movie

    flash[:danger] = t ".not_found"
    redirect_to root_path
  end

  rescue_from CanCan::AccessDenied do |exception|
    flash[:alert] = exception.message
    redirect_to root_path
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
  def star score
    link_to rates_path(score: score, movie_id: @movie.id), method: :post,
                      class: "click-rate", remote: true do
      content_tag(:span, "☆")
    end
  end

  def option_status_movie
    Movie.statuses.map{|key, value| [t(".#{key}"), value]}
  end
end

app/views/movies/_cast.html.erb
<div class="col-2 list_movie">
  <%= link_to "" do %>
    <div class="card card-block">
      <%= image_tag cast.avatar, class: "card-img-top" %>
      <div class="card-body">
        <h5 class="card-title text-dark"><b><%= cast.cast_name %></b></h5>
        <p class="card-text text-secondary">
          <%= cast.birthday.strftime Settings.movie.birthday %>
        </p>
      </div>
    </div>
  <% end %>
</div>

app/views/movies/_movie.html.erb
<div class="col-2 list_movie">
  <%= link_to movie_path slug: movie.slug do %>
  <div class="card card-block card-movie" id="card">
    <%= image_tag movie.image.to_s,class: "card-img-top"%>
    <div class="card-body">
      <h5 class="card-title text-dark"><b><%= movie.title %></b></h5>
      <p class="card-text text-secondary"><%= movie.release_date %></p>
    </div>
  </div>
  <% end %>
</div>

app/views/movies/_social.html.erb
<div class="row w-75" id="social">
  <div class="col-3">
    <div class="row">
      <div class="col-5">
        <div class="scores" id="score">
          <%= render partial: "rates/score", movie: @movie %>
        </div>
      </div>
      <div class="col-4">
        <p id="user-score"><%= t ".user_score" %></p>
      </div>
    </div>
  </div>
  <div class="col-1 icon-movie" id="bookmark_movies" >
    <%= render partial: "bookmark_movies/bookmark", movie: @movie %>
  </div>

  <div class="col-1 icon-movie" id="favoriate-movie">
    <%= render partial: "favoriate_movies/favoriate", movie: @movie %>
  </div>

  <div class="col-1 icon-movie-rated" id="rating-movie" >
    <%= render partial: "rates/rate", movie: @movie %>
  </div>
</div>

<div class="row" id="rate-show">
  <div class="col-4">
  </div>
  <div class="col-5">
    <div class="row rating d-flex justify-content-around" >
      <%= for x in 5.downto 1 do %>
        <%= star x %>
      <% end %>
    </div>
  </div>
  <div class="col-3">
  </div>
</div>

app/views/movies/_trailer.html.erb
<div class="col-3 list_movie">
  <%= link_to "", data: {toggle: "modal", target: "#"+movie.slug } do %>
    <%= image_tag movie.background_url.to_s, class: "card-img-top fa fa-play-circle" %>
    <div class="play"><i class="fa fa-play" aria-hidden="true"></i></div>
    <br>
    <h5 class="card-title text-white text-center"><b><%= movie.title %></b></h5>
  <% end %>
  <br>
</div>
<div class="modal fade" id="<%= movie.slug %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content modal-dialog-centered">
      <iframe id="glassAnimalsVideo" src="<%= movie.trailer %>" frameborder="0" allowfullscreen></iframe>
    </div>
  </div>
</div>

app/views/movies/index.html.erb
<div class="container-fluid big-search">
  <div class="search-box">
    <div>
      <h2 class="text-white font-weight-bold"><%= t ".welcome" %></h2>
      <h3 class="text-white font-weight-bold"><%= t ".introduce" %></h3>
    </div>
    <br>
    <%= search_form_for @q, url: search_index_path, html: {method: :get, class:"search-form form row"} do |f| %>
      <label>
        <%= f.search_field :info_movie_cont, class: "search-field", placeholder: t(".search_movies"), autocomplete: "off" %>
      </label>
      <%= submit_tag t(".search"), name: nil, class: "search-submit button" %>
    <% end %>
    <br>
  </div>
</div>
<br>
<br>
<div class="container-fluid content">
  <h4><b><%= t ".popular" %></b></h4>
  <div class="row flex-nowrap">
    <%= render @movies %>
  </div>
</div>
<br>

<!--Trailer-->
<div class="container-fluid trailer">
  <h4 class="text-white title-trailer"><b><%= t ".trailers" %></b></h4>
  <div class="row flex-nowrap content-trailer">
    <%= render partial: "trailer", collection: @movies, as: :movie %>
  </div>
</div>
<br>
<div class="container-fluid content">
  <h4><b><%= t ".trending" %></b></h4>
  <div class="row flex-nowrap">
    <%= render @movies %>
  </div>
</div>

app/views/movies/show.html.erb
<div id="redirect">
  <%= render "shared/redirect"%>
  <span id="back">
    <%= link_to @movie.title, movie_path(@movie.slug) %>
  </span>
</div>
<div class="background_preview">
  <div class="row content_img">
    <div class="col-4 d-flex justify-content-center align-items-center">
      <%= image_tag @movie.image_url, id: "image_singlemovie" %>
    </div>
    <div class="col-8 content_text">
      <br>
      <div class="title">
        <%= link_to @movie.title, "#" %>
        <span>(<%= @movie.release_date.strftime Settings.movie.date %>)</span>
      </div>
      <div class="facts">
        <span><%= @movie.release_date %> - </span>
        <span><%= @movie.genre_name %> - </span>
        <span><%= @movie.runtime %> - </span>
        <span><%= @movie.view %></span>
        <span><%= t ".views" %></span>
      </div>

      <br>
      <%= render "social" %>
      <br>

    <div class="header_info">
      <h4><%= t ".overview" %></h4>
      <p><%= @movie.overview %></p>
      <p id="director"><%= t ".director" %></p>
      <span><%= @movie.director %></span>
    </div>
    <br>
    <div>
      <%= link_to t(".play_trailer"), "", data: {toggle: "modal", target: "#"+@movie.slug }, class:"btn btn-light play", id:"play-movie" %>
      <%= link_to t(".play_movie"), watch_path, class:"btn btn-info", id:"play-movie" %>
    </div>
  </div>
</div>

<div class="container-fluid content">
  <h4><b><%= t ".top-casts" %></b> </h4>
  <div class="row flex-nowrap">
    <%= render partial: "cast", collection: @movie.casts, as: :cast %>
  </div>
</div>
<br>

<div class="container" id="comment">
  <h3><b><%= t ".comment" %></b></h3>
  <div class="card">
    <div class="row">
      <div class="col-md-1">
        <%= image_tag "icon-logo.jpg", class:"img-comment-first" %>
      </div>
      <div class="col-10 col-md-offset-3">
          <div class="panel panel-info">
            <div class="panel-body all-parent">
              <%= render partial: "comments/form", locals: {commentable: @movie}  %>
            </div>
          </div>
      </div>
    </div>

    <div class="card-body" id="all-parent-cmt" >
      <%= render partial: "comments/comment", collection: @movie.comments, as: :commentable %>
    </div>
  </div>
</div>

<div class="container-fluid content">
  <h4><b><%= t ".recommendations" %></b></h4>
  <div class="row flex-nowrap">
    <%= render partial: "movie", collection: @recommend.movies, as: :movie %>
  </div>
</div>
<br>

<div class="modal fade" id="<%= @movie.slug %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content modal-dialog-centered">
      <iframe id="glassAnimalsVideo" src="<%= @movie.trailer %>" frameborder="0" allowfullscreen></iframe>
    </div>
  </div>
</div>

app/views/movies/watch.html.erb
<div class="container-fluid" id="page-wath">
  <div class="container" id="watch" >
    <div class="row">
      <%= video_tag @movie.film_url.to_s, controls: true, id: "watch-film" %>
    </div>
    <div class="row" id="title">
      <%= link_to @movie.title, movie_path(@movie.slug), class:"text-white font-weight-bold", id: "title-watch" %>
      <h5 class="text-white" id="year">(<%= @movie.release_date.strftime Settings.movie.date %>)</p>
      <h5 class="text-white"><%= number_with_delimiter(@movie.view) %></h5>
      <span class="text-white" id="views"><%= t(".views") %><span>
    </div>
  </div>

  <div class="container" id="comment">
    <h3 class="text-white"><%= t ".comment" %></h3>
    <div class="card">
      <div class="row">
        <div class="col-md-1">
          <%= image_tag "icon-logo.jpg", class:"img-comment-first" %>
        </div>
        <div class="col-10 col-md-offset-3">
            <div class="panel panel-info">
              <div class="panel-body all-parent">
                <%= render partial: "comments/form", locals: {commentable: @movie}  %>
              </div>
            </div>
        </div>
      </div>

      <div class="card-body" id="all-parent-cmt" >
        <%= render partial: "comments/comment", collection: @movie.comments, as: :commentable %>
      </div>
    </div>
  </div>
</div>