config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"
  devise_for :users, only: :omniauth_callbacks,
             controllers: {omniauth_callbacks: "users/omniauth_callbacks"}

  scope "(:locale)", locale: /en|vi/ do

    devise_for :users, skip: :omniauth_callbacks, controllers: {
      registrations: "users/registrations",
      sessions: "users/sessions",
      passwords: "users/passwords"
    }
    resources :upgrade_accounts, only: :update

    root "movies#index"
    get "/movies/:slug", to: "movies#show", as: :movie
    get "/movies/watch/:slug", to: "movies#watch", as: :watch

    resources :search, only: :index

    resources :favoriate_movies, :bookmark_movies, only: %i(index create destroy)

    resources :rates, only: %i(create destroy)

    resources :movies do
      resources :comments, only: %i(create destroy)
    end
    resources :comments do
      resources :comments, only: %i(create destroy)
    end

    namespace :admin do
      root "dashboards#index"
      resources :movies do
        patch "lock", on: :member
      end
      resources :notifications do
        post "read_all", on: :collection
      end
    end
    match "*unmatched", to: "application#rescue_404_exception", via: :all
  end
end

app/controllers/admin/movies_controller.rb
class Admin::MoviesController < AdminController
  authorize_resource
  before_action :find_movie, except: %i(index create new)
  before_action :load_data, only: %i(index new edit)
  before_action :load_notify, only: :index

  def index
    @q = Movie.unscoped.ordered_by_create
              .search params[:q], auth_object: set_ransack_auth_object
    @movies = @q.result.includes(:genre).page(params[:page]).per Settings.five
  end

  def new
    @movie = Movie.unscoped.new
  end

  def create
    @movie = Movie.unscoped.new movie_params
    if @movie.save
      flash[:success] = ".success"
      redirect_to admin_movies_path
    else
      flash.now[:danger] = ".error"
      render :new
    end
  end

  def edit; end

  def update
    if @movie.update movie_params
      flash[:success] = ".movie_updated"
      redirect_to admin_movies_path
    else
      flash[:danger] = t ".movie_update_fail"
      render :edit
    end
  end

  def destroy
    if @movie.destroy
      flash[:success] = t ".movie_deleted"
    else
      flash[:danger] = t ".fail"
    end
    respond_to :js
  end

  def lock
    if @movie.update status: params[:status]
      UserWorker.perform_async @movie.id
      flash[:success] = t ".success"
    else
      flash[:danger] = t ".fail"
    end
    respond_to :js
  end

  private

  def movie_params
    params.require(:movie).permit Movie::MOVIE_PERMIT
  end

  def find_movie
    @movie = Movie.unscoped.find params[:id]
  end

  def load_data
    @genre = Genre.all
  end

  def load_notify
    @notification = Notification.unread.ordered_by_create
                                .page(params[:page]).per Settings.five
  end

  def set_ransack_auth_object
    :admin if current_user.admin?
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  load_and_authorize_resource

  def index
    @q = Movie.ransack params[:q]
    @movies = @q.result.ordered_by_view.page(params[:page]).per Settings.five
  end

  def show
    @movie = Movie.includes(:casts).find_by slug: params[:slug]
    @recommend = Genre.includes(:movies).find_by id: @movie.genre_id
  end

  def watch
    @movie = Movie.find_by slug: params[:slug]
    Movie.update_counters [@movie.id], view: Settings.movie.inc_view_per
    @comments = @movie.comments

    return if @movie

    flash[:danger] = t ".not_found"
    redirect_to root_path
  end

  rescue_from CanCan::AccessDenied do |exception|
    flash[:alert] = exception.message
    redirect_to root_path
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
  def star score
    link_to rates_path(score: score, movie_id: @movie.id), method: :post,
                      class: "click-rate", remote: true do
      content_tag(:span, "☆")
    end
  end

  def option_status_movie
    Movie.statuses.map{|key, value| [t(".#{key}"), value]}
  end
end

app/views/admin/layouts/movies/_lock.html.erb
<% if movie.lock_movie? %>
  <%= link_to lock_admin_movie_path(movie.id, status: "open"), method: :patch, remote: true do %>
    <%= fa_icon "lock", id:"color-lock"  %>
  <% end %>
<% else %>
  <%= link_to lock_admin_movie_path(movie.id, status: "lock_movie"), method: :patch, remote: true  do %>
    <%= fa_icon "unlock", id:"color-unlock" %>
  <% end %>
<% end %>

app/views/admin/layouts/movies/_read.html.erb
<!-- Modal -->
<div class="modal fade" id="<%= movie.slug %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content" id="modal-read">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle"><%= t ".detail_movie" %> </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <table class="table table-borderless ">
          <tbody>
            <tr>
              <th><%= t ".title" %></th>
              <td><%= movie.title %> </td>
            </tr>
            <tr>
              <th><%= t ".image" %></th>
              <td><%= image_tag movie.image_url.to_s, id:"img-read" %> </td>
            </tr>
            <tr>
              <th><%= t ".background_image" %></th>
              <td>
                 <%= image_tag movie.background_url.to_s, id:"img-background" %>
              </td>
            </tr>
            <tr>
              <th><%= t ".slug" %></th>
              <td><%= movie.slug %></td>
            </tr>
            <tr>
              <th><%= t ".overview" %></th>
              <td><%= movie.overview %></td>
            </tr>
            <tr>
              <th><%= t ".genre" %></th>
              <td><%= movie.genre_name %></td>
            </tr>
            <tr>
              <th><%= t ".runtime" %></th>
              <td><%= movie.runtime %></td>
            </tr>
            <tr>
              <th><%= t ".director" %></th>
              <td><%= movie.director %></td>
            </tr>
            <tr>
              <th><%= t ".release_date" %></th>
              <td><%= movie.release_date %></td>
            </tr>
            <tr>
              <th><%= t ".trailer" %></th>
              <td>
                <iframe id="trailer" src="<%= movie.trailer %>" frameborder="0"
                  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                  allowfullscreen>
                </iframe>
              </td>
            </tr>
            <tr>
              <th><%= t ".movie" %></th>
            <td><%= video_tag movie.film_url.to_s, controls: true, id: "film"%></td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">
          <%= t ".close" %>
        </button>
      </div>
    </div>
  </div>
</div>