config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"
  devise_for :users, only: :omniauth_callbacks,
             controllers: {omniauth_callbacks: "users/omniauth_callbacks"}

  scope "(:locale)", locale: /en|vi/ do

    devise_for :users, skip: :omniauth_callbacks, controllers: {
      registrations: "users/registrations",
      sessions: "users/sessions",
      passwords: "users/passwords"
    }
    resources :upgrade_accounts, only: :update

    root "movies#index"
    get "/movies/:slug", to: "movies#show", as: :movie
    get "/movies/watch/:slug", to: "movies#watch", as: :watch

    resources :search, only: :index

    resources :favoriate_movies, :bookmark_movies, only: %i(index create destroy)

    resources :rates, only: %i(create destroy)

    resources :movies do
      resources :comments, only: %i(create destroy)
    end
    resources :comments do
      resources :comments, only: %i(create destroy)
    end

    namespace :admin do
      root "dashboards#index"
      resources :movies do
        patch "lock", on: :member
      end
      resources :notifications do
        post "read_all", on: :collection
      end
    end
    match "*unmatched", to: "application#rescue_404_exception", via: :all
  end
end

app/controllers/admin/movies_controller.rb
class Admin::MoviesController < AdminController
  authorize_resource
  before_action :find_movie, except: %i(index create new)
  before_action :load_data, only: %i(index new edit)
  before_action :load_notify, only: :index

  def index
    @q = Movie.unscoped.ordered_by_create
              .search params[:q], auth_object: set_ransack_auth_object
    @movies = @q.result.includes(:genre).page(params[:page]).per Settings.five
  end

  def new
    @movie = Movie.unscoped.new
  end

  def create
    @movie = Movie.unscoped.new movie_params
    if @movie.save
      flash[:success] = ".success"
      redirect_to admin_movies_path
    else
      flash.now[:danger] = ".error"
      render :new
    end
  end

  def edit; end

  def update
    if @movie.update movie_params
      flash[:success] = ".movie_updated"
      redirect_to admin_movies_path
    else
      flash[:danger] = t ".movie_update_fail"
      render :edit
    end
  end

  def destroy
    if @movie.destroy
      flash[:success] = t ".movie_deleted"
    else
      flash[:danger] = t ".fail"
    end
    respond_to :js
  end

  def lock
    if @movie.update status: params[:status]
      UserWorker.perform_async @movie.id
      flash[:success] = t ".success"
    else
      flash[:danger] = t ".fail"
    end
    respond_to :js
  end

  private

  def movie_params
    params.require(:movie).permit Movie::MOVIE_PERMIT
  end

  def find_movie
    @movie = Movie.unscoped.find params[:id]
  end

  def load_data
    @genre = Genre.all
  end

  def load_notify
    @notification = Notification.unread.ordered_by_create
                                .page(params[:page]).per Settings.five
  end

  def set_ransack_auth_object
    :admin if current_user.admin?
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  load_and_authorize_resource

  def index
    @q = Movie.ransack params[:q]
    @movies = @q.result.ordered_by_view.page(params[:page]).per Settings.five
  end

  def show
    @movie = Movie.includes(:casts).find_by slug: params[:slug]
    @recommend = Genre.includes(:movies).find_by id: @movie.genre_id
  end

  def watch
    @movie = Movie.find_by slug: params[:slug]
    Movie.update_counters [@movie.id], view: Settings.movie.inc_view_per
    @comments = @movie.comments

    return if @movie

    flash[:danger] = t ".not_found"
    redirect_to root_path
  end

  rescue_from CanCan::AccessDenied do |exception|
    flash[:alert] = exception.message
    redirect_to root_path
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
  def star score
    link_to rates_path(score: score, movie_id: @movie.id), method: :post,
                      class: "click-rate", remote: true do
      content_tag(:span, "☆")
    end
  end

  def option_status_movie
    Movie.statuses.map{|key, value| [t(".#{key}"), value]}
  end
end

app/views/admin/movies/_cast_fields.html.erb
<div class="nested-fields">
  <%= f.label :cast_name %>
  <%= f.text_field :cast_name, class: "form-control-file" %>

  <%= f.label :birthday %>
  <%= f.date_field :birthday, class: "form-control-file" %>

  <%= f.label :birthplace %>
  <%= f.text_field :birthplace, class: "form-control-file" %>

  <%= f.label :avatar %>
  <%= f.file_field :avatar, class: "form-control-file" %>

  <%= link_to_remove_association t(".remove"), f, class: "btn btn-danger" %>
</div>

app/views/admin/movies/_form.html.erb
<%= form_for [:admin, @movie] do |f| %>
  <%= render "admin/shared/error_messages" %>
  <%= f.label :title, class:"control-label-required" %>
  <%= f.text_field :title, class: "form-control "%>

  <%= f.label :slug, class:"control-label-required" %>
  <%= f.text_field :slug, class: "form-control" %>

  <%= f.label :overview %>
  <%= f.text_area :overview, class: "form-control", rows:"4" %>

  <%= f.label :genre, class:"control-label-required" %>

  <%= f.select :genre_id, options_from_collection_for_select(Genre.all, "id", "genre_name",  @movie.genre_id), {}, {class: "form-control"} %>

  <%= f.label :runtime, class:"control-label-required" %>
  <%= f.text_field :runtime, class: "form-control" %>

  <%= f.label :director %>
  <%= f.text_field :director, class: "form-control" %>

  <%= f.label :trailer, class:"control-label-required" %>
  <%= f.text_field :trailer, class: "form-control" %>

  <%= f.label :release_date %>
  <%= f.text_field :release_date, type:"date", class: "form-control" %>

  <%= f.label :image, class:"control-label-required" %>
  <%= f.file_field :image, class: "form-control-file"%>

  <%= f.label :background_image %>
  <%= f.file_field :background, class: "form-control-file" %>

  <%= f.label :movie %>
  <%= f.file_field :film, class: "form-control-file" %>
  <hr>

  <h4><%= t ".add_cast" %></h4>
  <%= f.fields_for :casts do |cast| %>
    <%= render "cast_fields", f: cast %>
    <hr>
  <% end %>

  <div class="links">
    <%= link_to_add_association t(".add_cast"), f, :casts, {class: "btn btn-primary"} %>
  </div>

  <br>
  <div class="text-center text-bold">
    <%= link_to t(".cancel"), admin_movies_path, class: "btn btn-secondary" %>
    <%= f.submit t(".save"), class: "btn btn-success font-weight-bold" %>
  </div>
<% end %>

app/views/admin/movies/_movie.html.erb
<tr id="movie-<%= movie.id %>">
  <td class="counterCell" scope="row"></td>
  <td><%= movie.title %></td>
  <td class="text-truncate" id="img-film">
    <%= image_tag movie.image_url.to_s, id:"movie_img" %>
  </td>
  <td><%= movie.slug %></td>
  <td class="text-truncate" id="truncate"><%= movie.overview %></td>
  <td class="text-truncate" id="truncate"><%= movie.genre_name %></td>
  <td><%= movie.runtime %></td>
  <td><%= movie.director %></td>
  <td><%= movie.release_date %></td>
  <td id="action">
    <%= link_to "", data: {toggle: "modal", target: "#"+movie.slug} do %>
      <%= fa_icon "eye", id:"eye" %>
    <% end %>
    &nbsp;
    &nbsp;
    <%= link_to "movies/#{movie.id}/edit" do %>
      <%= fa_icon "pencil-square-o", id:"pencil" %>
    <% end %>
    &nbsp;
    &nbsp;
    <%= link_to admin_movie_path(movie), method: :delete, data: { confirm: t(".sure") }, remote: true do %>
      <%= fa_icon "trash", id:"trash" %>
    <% end %>
    &nbsp;
    &nbsp;
    <span id="lock-<%= movie.id %>" class="lock">
      <%= render "admin/layouts/movies/lock", movie: movie %>
    </span>

    <%= render "admin/layouts/movies/read", movie: movie %>
  </td>
</tr>

app/views/admin/movies/destroy.js.erb
$('#movie-<%= @movie.id %>').remove();
$('#toastr').html('<%= j render "shared/toastr" %>');

app/views/admin/movies/edit.html.erb
<section class="content">
  <div class="row justify-content-center">
    <div class="col-11">
      <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title"><%= t ".update_movie" %></h3>
        </div>
        <div class="card-body">
          <%= render "form" %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/admin/movies/index.html.erb
<div class="row" id="search-box" >
  <%= search_form_for @q, url: admin_movies_path, method: :get, remote: true do |f| %>
    <div class="input-group input-group-sm">
      <%= f.label :created_at_date %>
      <%= f.search_field :created_at_date_equals, type: "date", class: "created_at" %>
      <%= f.search_field :info_movie_cont, class:"form-control", placeholder: t(".info_movie") %>
      <%= f.select :status_eq, options_for_select(option_status_movie), {include_blank: t(".all"), class: "form-control"} %>

      <%= button_tag(type: "submit", class: "btn btn-info") do %>
        <%= fa_icon "search" %>
      <% end %>
    </div>
  <% end %>
</div>

<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="row card-header">
            <div class="card-title col-11">
              <h3><%= t ".header" %></h3>
            </div>
            <div class="col-1">
              <%= link_to t(".add"), new_admin_movie_path, class: "btn btn-info" %>
            </div>
          </div>
          <div class="card-body">
            <table id="example2" class="table table-bordered table-hover">
              <thead>
                <tr>
                  <th id="stt">#</th>
                  <th id="title">
                    <%= sort_link @q, :title %>
                  </th>
                  <th><%= t ".image" %></th>
                  <th><%= t ".slug" %></th>
                  <th><%= t ".overview" %></th>
                  <th><%= t ".genre" %></th>
                  <th><%= t ".runtime" %></th>
                  <th><%= t ".director" %></th>
                  <th id="release_date">
                    <%= sort_link @q, :release_date %>
                  </th>
                  <th><%= t ".action" %></th>
                </tr>
              </thead>
              <h5><%= t ".total" %> :<span id="total-search"><%= @movies.total_count %></span></h5>

              <tbody id="text-search">
                <%= render @movies %>
              </tbody>
            </table>
            &nbsp;
            <div class="d-flex justify-content-center" id="paginate-search" >
              <%= paginate @movies %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/admin/movies/index.js.erb
$('#text-search').html('<%= j render @movies %>');
$('#total-search').html('<%= j @movies.total_count %>');
$('#paginate-search').html('<%= j paginate @movies %>');

app/views/admin/movies/lock.js.erb
$('#lock-<%= @movie.id %>').html('<%= j render "admin/layouts/movies/lock", movie: @movie %>');
$('#toastr').html('<%= j render "shared/toastr" %>');

app/views/admin/movies/new.html.erb
<section class="content">
  <div class="row justify-content-center">
    <div class="col-11">
      <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title"><%= t ".create_new" %></h3>
        </div>
        <div class="card-body">
          <%= render "form" %>
        </div>
      </div>
    </div>
  </div>
</section>